export const mockStudents = [
    // High Performers
    {
        _id: "1",
        name: "Aisha Patel",
        email: "aisha.patel@university.edu",
        phone: "+1-555-0101",
        course: "Computer Science",
        enrollmentDate: "2022-09-01",
        status: "Active",
        address: "123 Tech Boulevard",
        city: "San Francisco",
        country: "USA",
        zipCode: "94102",
        gpa: "4.0"
    },
    {
        _id: "2",
        name: "Marcus Johnson",
        email: "m.johnson@university.edu",
        phone: "+1-555-0102",
        course: "Electrical Engineering",
        enrollmentDate: "2022-09-01",
        status: "Active",
        address: "456 Innovation Drive",
        city: "Boston",
        country: "USA",
        zipCode: "02101",
        gpa: "3.95"
    },
    // International Students
    {
        _id: "3",
        name: "Yuki Tanaka",
        email: "yuki.t@university.edu",
        phone: "+81-90-1234-5678",
        course: "Mechanical Engineering",
        enrollmentDate: "2023-01-15",
        status: "Active",
        address: "789 Sakura Street",
        city: "Tokyo",
        country: "Japan",
        zipCode: "100-0001",
        gpa: "3.88"
    },
    {
        _id: "4",
        name: "Sofia Rodriguez",
        email: "sofia.r@university.edu",
        phone: "+34-612-345-678",
        course: "Business Administration",
        enrollmentDate: "2023-02-01",
        status: "Active",
        address: "321 Plaza Mayor",
        city: "Madrid",
        country: "Spain",
        zipCode: "28001",
        gpa: "3.75"
    },
    // Graduated Students
    {
        _id: "5",
        name: "David Chen",
        email: "david.chen@alumni.edu",
        phone: "+1-555-0105",
        course: "Data Science",
        enrollmentDate: "2020-09-01",
        status: "Graduated",
        address: "654 Analytics Avenue",
        city: "Seattle",
        country: "USA",
        zipCode: "98101",
        gpa: "3.92"
    },
    {
        _id: "6",
        name: "Emma Williams",
        email: "emma.w@alumni.edu",
        phone: "+1-555-0106",
        course: "Medicine",
        enrollmentDate: "2019-09-01",
        status: "Graduated",
        address: "987 Healthcare Lane",
        city: "New York",
        country: "USA",
        zipCode: "10001",
        gpa: "3.98"
    },
    // Average Performers
    {
        _id: "7",
        name: "Mohammed Al-Rashid",
        email: "m.alrashid@university.edu",
        phone: "+971-50-123-4567",
        course: "Civil Engineering",
        enrollmentDate: "2023-03-10",
        status: "Active",
        address: "147 Desert Road",
        city: "Dubai",
        country: "UAE",
        zipCode: "00000",
        gpa: "3.45"
    },
    {
        _id: "8",
        name: "Isabella Santos",
        email: "isabella.s@university.edu",
        phone: "+55-11-98765-4321",
        course: "Architecture",
        enrollmentDate: "2023-01-20",
        status: "Active",
        address: "258 Copacabana Avenue",
        city: "Rio de Janeiro",
        country: "Brazil",
        zipCode: "22000-000",
        gpa: "3.30"
    },
    {
        _id: "9",
        name: "James O'Connor",
        email: "james.o@university.edu",
        phone: "+353-87-123-4567",
        course: "Literature",
        enrollmentDate: "2022-10-01",
        status: "Active",
        address: "369 Trinity Street",
        city: "Dublin",
        country: "Ireland",
        zipCode: "D02",
        gpa: "3.25"
    },
    {
        _id: "10",
        name: "Priya Sharma",
        email: "priya.sharma@university.edu",
        phone: "+91-98765-43210",
        course: "Biotechnology",
        enrollmentDate: "2023-02-15",
        status: "Active",
        address: "741 Tech Park",
        city: "Bangalore",
        country: "India",
        zipCode: "560001",
        gpa: "3.60"
    },
    // Lower Performers / At Risk
    {
        _id: "11",
        name: "Tyler Brooks",
        email: "tyler.b@university.edu",
        phone: "+1-555-0111",
        course: "Psychology",
        enrollmentDate: "2023-04-01",
        status: "Active",
        address: "852 Campus Drive",
        city: "Austin",
        country: "USA",
        zipCode: "78701",
        gpa: "2.85"
    },
    {
        _id: "12",
        name: "Nina Kowalski",
        email: "nina.k@university.edu",
        phone: "+48-601-234-567",
        course: "Fine Arts",
        enrollmentDate: "2023-03-15",
        status: "Active",
        address: "963 Culture Street",
        city: "Warsaw",
        country: "Poland",
        zipCode: "00-001",
        gpa: "2.95"
    },
    // Inactive Students
    {
        _id: "13",
        name: "Alex Thompson",
        email: "alex.t@university.edu",
        phone: "+1-555-0113",
        course: "Economics",
        enrollmentDate: "2022-09-01",
        status: "Inactive",
        address: "159 Market Street",
        city: "Chicago",
        country: "USA",
        zipCode: "60601",
        gpa: "2.50"
    },
    {
        _id: "14",
        name: "Olivia Martinez",
        email: "olivia.m@university.edu",
        phone: "+1-555-0114",
        course: "Sociology",
        enrollmentDate: "2023-01-10",
        status: "Inactive",
        address: "357 University Ave",
        city: "Miami",
        country: "USA",
        zipCode: "33101",
        gpa: "2.75"
    },
    // Suspended Students
    {
        _id: "15",
        name: "Ryan Mitchell",
        email: "ryan.m@university.edu",
        phone: "+1-555-0115",
        course: "Political Science",
        enrollmentDate: "2023-02-20",
        status: "Suspended",
        address: "753 Capitol Hill",
        city: "Washington DC",
        country: "USA",
        zipCode: "20001",
        gpa: "1.95"
    },
    {
        _id: "16",
        name: "Chloe Anderson",
        email: "chloe.a@university.edu",
        phone: "+1-555-0116",
        course: "Chemistry",
        enrollmentDate: "2023-03-01",
        status: "Suspended",
        address: "951 Science Park",
        city: "Denver",
        country: "USA",
        zipCode: "80201",
        gpa: "2.10"
    },
    // More Active Students (Diverse Courses)
    {
        _id: "17",
        name: "Lucas Müller",
        email: "lucas.m@university.edu",
        phone: "+49-151-2345-6789",
        course: "Physics",
        enrollmentDate: "2022-10-15",
        status: "Active",
        address: "147 Einstein Strasse",
        city: "Munich",
        country: "Germany",
        zipCode: "80331",
        gpa: "3.70"
    },
    {
        _id: "18",
        name: "Amara Okafor",
        email: "amara.o@university.edu",
        phone: "+234-803-123-4567",
        course: "Environmental Science",
        enrollmentDate: "2023-01-25",
        status: "Active",
        address: "258 Victoria Island",
        city: "Lagos",
        country: "Nigeria",
        zipCode: "101001",
        gpa: "3.55"
    },
    {
        _id: "19",
        name: "Ethan Kim",
        email: "ethan.kim@university.edu",
        phone: "+82-10-1234-5678",
        course: "Artificial Intelligence",
        enrollmentDate: "2023-02-10",
        status: "Active",
        address: "369 Gangnam Avenue",
        city: "Seoul",
        country: "South Korea",
        zipCode: "06000",
        gpa: "3.82"
    },
    {
        _id: "20",
        name: "Zara Hassan",
        email: "zara.h@university.edu",
        phone: "+20-100-123-4567",
        course: "History",
        enrollmentDate: "2022-11-01",
        status: "Active",
        address: "741 Nile Street",
        city: "Cairo",
        country: "Egypt",
        zipCode: "11511",
        gpa: "3.40"
    },
    // Additional Graduated
    {
        _id: "21",
        name: "Benjamin Lee",
        email: "ben.lee@alumni.edu",
        phone: "+1-555-0121",
        course: "Law",
        enrollmentDate: "2019-09-01",
        status: "Graduated",
        address: "852 Justice Boulevard",
        city: "Los Angeles",
        country: "USA",
        zipCode: "90001",
        gpa: "3.85"
    },
    {
        _id: "22",
        name: "Fatima Al-Sayed",
        email: "fatima.a@alumni.edu",
        phone: "+966-50-123-4567",
        course: "Pharmacy",
        enrollmentDate: "2020-01-15",
        status: "Graduated",
        address: "963 Medical District",
        city: "Riyadh",
        country: "Saudi Arabia",
        zipCode: "11564",
        gpa: "3.90"
    }
];
